name: Build TrollInstallerX IPA

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install ldid
        run: brew install ldid

      - name: Build and Package IPA
        run: |
          set -e

          xcodebuild -configuration Release -derivedDataPath DerivedData/TrollInstallerX -destination 'generic/platform=iOS' -scheme TrollInstallerX CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY=""
          cp Resources/ents.plist DerivedData/TrollInstallerX/Build/Products/Release-iphoneos/
          pushd DerivedData/TrollInstallerX/Build/Products/Release-iphoneos
          rm -rf Payload TrollInstallerX.ipa
          mkdir Payload
          cp -r TrollInstallerX.app Payload
          ldid -Sents.plist Payload/TrollInstallerX.app
          zip -qry TrollInstallerX.ipa Payload
          popd
          cp DerivedData/TrollInstallerX/Build/Products/Release-iphoneos/TrollInstallerX.ipa .
          rm -rf Payload

      - name: Upload IPA Artifact
        uses: actions/zip-release@v3
        if: always()
        with:
          type: 'zip'
          filename: 'TrollInstallerX-Build.zip'
          path: 'TrollInstallerX.ipa'
